In [1]:
import os 
import geopandas as gpd

The tasks today are to remove rows with a set of criteria belwo:
- if CODE1=AL013, CODE2=AQ063,and ANNOTATION=Illegal Shared Face error: Building, then remove it
- if CODE1= AL260,CODE2=BA010,and ANNOTATION=Illegal Shared Curve error: Fence,then remove it

# 1. Read the shapefile

In [11]:
# Load the data
path=r"C:\Users\DELL\OneDrive - tuaf.edu.vn\TUAF\Python_Tutorial\DAAD Scholarship\consolidated1PT.shp"

myfile = gpd.read_file(path)
myfile.head()

,ERRTYPE,MAGNITUDE,INSTANCE,COND_NUM,CODE1,CODE2,LABEL1,LABEL2,ANNOTATION,ORIG_GEOM,...,RETAINIGN,COR_TECH,COR_DATE,C_COMMENTS,VER_TECH,VER_DATE,V_COMMENTS,ORIG_FID,ORIG_TABLE,geometry
0,Line - Line Undershoot,0.123691,31,1,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,RETAIN,None,None,None,None,None,None,390,TRAIL_C,POINT (50.86560 28.93991)
1,Line - Line Undershoot,0.130404,31,2,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,RETAIN,None,None,None,None,None,None,386,TRAIL_C,POINT (50.86592 28.93937)
2,Line - Line Undershoot,0.194444,31,3,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,RETAIN,None,None,None,None,None,None,552,TRAIL_C,POINT (50.86710 28.93712)
3,Line - Line Undershoot,0.244684,31,4,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,RETAIN,None,None,None,None,None,None,391,TRAIL_C,POINT (50.86638 28.93837)
4,Line - Line Undershoot,0.254737,31,5,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,RETAIN,None,None,None,None,None,None,387,TRAIL_C,POINT (50.86698 28.93736)

In [13]:
# Check the unique values of ANNOTATION column

myfile.ANNOTATION.value_counts(dropna=False, sort=False)

Illegal Shared Face error: Island                                               1
Illegal Shared Face error: Fuel Storage Facility                                7
Illegal Shared Face error: Power Substation                                     1
Illegal Shared Face error: Embankment                                         116
Illegal Shared Face error: Orchard                                             20
                                                                             ...
Illegal Shared Face error: Cemetery                                             1
Line Cart Track intersects line Fence or Wall without a point or line Gate     24
Illegal Shared Face error: Helipad                                              7
Illegal Shared Face warning: Harbour                                            1
Illegal Shared Face error: Memorial Monument                                    1
Name: ANNOTATION, Length: 68, dtype: int64

In [15]:
# Calculate the number of unique values in a pandas.series 
print("The number of ANNOTATION unique value is {0}".format(myfile.ANNOTATION.nunique(dropna=False)))

The number of ANNOTATION unique value is 68

In [19]:
# Obtain of a list of ANNOTATION unique values

mlist=[]

for eachlitem in myfile.ANNOTATION.unique():
    mlist.append(eachlitem)
    
len(mlist)
# Encode each unique value with a unique number, ranging from 1 to 68

mdict={}

for eachline in myfile.ANNOTATION:
    if eachline in mdict:
        pass
    else:
        mdict[eachline]=len(mdict)+1

In [29]:
# Encode unique value and create a new column "ANNOTATION_Code" to myfile 
mcol=[]

for eachrow in myfile.ANNOTATION:
    for eachitem in mdict:
        if eachrow==eachitem:
            mcol.append(mdict["{0}".format(eachitem)])
        else:
            pass

myfile["ANNOTATION_Code"]=mcol

myfile.head(10)

,ERRTYPE,MAGNITUDE,INSTANCE,COND_NUM,CODE1,CODE2,LABEL1,LABEL2,ANNOTATION,ORIG_GEOM,...,COR_TECH,COR_DATE,C_COMMENTS,VER_TECH,VER_DATE,V_COMMENTS,ORIG_FID,ORIG_TABLE,geometry,ANNOTATION_Code
0,Line - Line Undershoot,0.123691,31,1,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,None,None,None,None,None,None,390,TRAIL_C,POINT (50.86560 28.93991),1
1,Line - Line Undershoot,0.130404,31,2,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,None,None,None,None,None,None,386,TRAIL_C,POINT (50.86592 28.93937),1
2,Line - Line Undershoot,0.194444,31,3,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,None,None,None,None,None,None,552,TRAIL_C,POINT (50.86710 28.93712),1
3,Line - Line Undershoot,0.244684,31,4,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,None,None,None,None,None,None,391,TRAIL_C,POINT (50.86638 28.93837),1
4,Line - Line Undershoot,0.254737,31,5,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,None,None,None,None,None,None,387,TRAIL_C,POINT (50.86698 28.93736),1
5,Line - Line Undershoot,0.476457,31,6,AP050,AP050,Trail,Trail,Undershoot involving line Trail,LINE,...,None,None,None,None,None,None,388,TRAIL_C,POINT (50.86678 28.93764),1
6,Line - Line Overshoot,0.904010,18,1,EA020,EA020,Hedgerow,Hedgerow,Overshoot involving line Hedgerow,LINE,...,None,None,None,None,None,None,931,HEDGEROW_C,POINT (50.82604 28.93878),2
7,Line - Line Overshoot,0.904010,18,1,EA020,EA020,Hedgerow,Hedgerow,Overshoot involving line Hedgerow,LINE,...,None,None,None,None,None,None,2421,HEDGEROW_C,POINT (50.82605 28.93878),2
8,Line - Line Overshoot,0.868839,22,1,AQ113,AQ113,Pipeline,Pipeline,Overshoot involving line Pipeline,LINE,...,None,None,None,None,None,None,98,PIPELINE_C,POINT (50.94958 28.92638),3
9,Line - Line Overshoot,0.000002,33,1,AL260,AL260,Wall,Wall,Overshoot involving line Wall,LINE,...,None,None,None,None,None,None,19256,WALL_C,POINT (50.83477 28.95613),4

# 2. Conduct the tasks

In [67]:
df=myfile[-myfile.CODE1.isin(["AL013","AL260"]) & -myfile.CODE2.isin(["AQ063","BA010"]) & -myfile.ANNOTATION_Code.isin([23,28])]
df.head()

,ERRTYPE,MAGNITUDE,INSTANCE,COND_NUM,CODE1,CODE2,LABEL1,LABEL2,ANNOTATION,ORIG_GEOM,...,COR_TECH,COR_DATE,C_COMMENTS,VER_TECH,VER_DATE,V_COMMENTS,ORIG_FID,ORIG_TABLE,geometry,ANNOTATION_Code
6,Line - Line Overshoot,0.904010,18,1,EA020,EA020,Hedgerow,Hedgerow,Overshoot involving line Hedgerow,LINE,...,None,None,None,None,None,None,931,HEDGEROW_C,POINT (50.82604 28.93878),2
7,Line - Line Overshoot,0.904010,18,1,EA020,EA020,Hedgerow,Hedgerow,Overshoot involving line Hedgerow,LINE,...,None,None,None,None,None,None,2421,HEDGEROW_C,POINT (50.82605 28.93878),2
8,Line - Line Overshoot,0.868839,22,1,AQ113,AQ113,Pipeline,Pipeline,Overshoot involving line Pipeline,LINE,...,None,None,None,None,None,None,98,PIPELINE_C,POINT (50.94958 28.92638),3
11,Line - Area Perimeter Undershoot,3.017963,1,1,BH030,BH030,Ditch,Ditch,"Line River, Canal, Aqueduct or Ditch undershoo...",LINE,...,None,None,None,None,None,None,218,DITCH_C,POINT (50.87724 28.92217),5
12,Line - Area Perimeter Undershoot,9.932716,1,2,BH030,BH030,Ditch,Ditch,"Line River, Canal, Aqueduct or Ditch undershoo...",AREA,...,None,None,None,None,None,None,2,DITCH_S,POINT (50.87601 28.92189),5